import Testing
@testable import CubeCore

@Test("V10/A02: all 54 URFDLB stickers occupy the documented 26-cubie lattice")
func cubeGeometryPlacements() throws {
  let cubies = CubeGeometry.cubies
  let stickers = CubeGeometry.stickers
  #expect(cubies.count == 26)
  try #require(stickers.count == 54)
  #expect(Set(cubies).count == 26)
  #expect(!cubies.contains(CubePosition(x: 0, y: 0, z: 0)))
  #expect(stickers.map(\.index) == Array(0..<54))
  // Handwritten positions from the specification's face/top-neighbor convention,
  // ordered URFDLB, with each face viewed from outside. Not generated by CubeGeometry.
  let expected: [[[Int]]] = [
    [[-1,1,-1],[0,1,-1],[1,1,-1],[-1,1,0],[0,1,0],[1,1,0],[-1,1,1],[0,1,1],[1,1,1]],
    [[1,1,1],[1,1,0],[1,1,-1],[1,0,1],[1,0,0],[1,0,-1],[1,-1,1],[1,-1,0],[1,-1,-1]],
    [[-1,1,1],[0,1,1],[1,1,1],[-1,0,1],[0,0,1],[1,0,1],[-1,-1,1],[0,-1,1],[1,-1,1]],
    [[-1,-1,1],[0,-1,1],[1,-1,1],[-1,-1,0],[0,-1,0],[1,-1,0],[-1,-1,-1],[0,-1,-1],[1,-1,-1]],
    [[-1,1,-1],[-1,1,0],[-1,1,1],[-1,0,-1],[-1,0,0],[-1,0,1],[-1,-1,-1],[-1,-1,0],[-1,-1,1]],
    [[1,1,-1],[0,1,-1],[-1,1,-1],[1,0,-1],[0,0,-1],[-1,0,-1],[1,-1,-1],[0,-1,-1],[-1,-1,-1]],
  ]
  let topEdges: [Face] = [.back, .up, .up, .front, .up, .up]
  for (index, sticker) in stickers.enumerated() {
    let face = index / 9
    let cell = index % 9
    #expect([sticker.position.x, sticker.position.y, sticker.position.z] == expected[face][cell])
    #expect(sticker.normal == Face.allCases[face])
    #expect(sticker.top == topEdges[face])
    #expect(cubies.contains(sticker.position))
  }
  let ownership = Dictionary(grouping: stickers, by: \.position)
  #expect(ownership.count == 26)
  #expect(ownership.values.filter { $0.count == 3 }.count == 8)
  #expect(ownership.values.filter { $0.count == 2 }.count == 12)
  #expect(ownership.values.filter { $0.count == 1 }.count == 6)
  for group in ownership.values {
    #expect(Set(group.map(\.normal)).count == group.count)
  }
}

@Test("V10: each visible face layer selects exactly nine cubies and 21 stickers in every pose")
func cubeGeometryLayerMembership() throws {
  for pose in CubeOrientation.all {
    let cubies = CubeGeometry.cubies.map { $0.viewed(at: pose) }
    let stickers = CubeGeometry.stickers.map { $0.viewed(at: pose) }
    for face in Face.allCases {
      let axis = pose.viewFace(for: face)
      let selected = cubies.filter { $0.isOnLayer(axis) }
      try #require(selected.count == 9)
      #expect(stickers.filter { $0.position.isOnLayer(axis) }.count == 21)
      #expect(selected.contains(CubeGeometry.axis(for: axis)))
      #expect(!selected.contains(CubeGeometry.axis(for: axis.opposite)))
    }
  }
}

@Test("V10: all 18 layer-turn endpoints in all 24 poses match independent golden sticker destinations")
func cubeGeometryTurns() throws {
  for pose in CubeOrientation.all {
    let before = CubeGeometry.stickers.map { $0.viewed(at: pose) }
    for face in Face.allCases {
      for turns in QuarterTurns.allCases {
        let rotation = CubeRotation(axis: pose.viewFace(for: face), turns: turns)
        for sticker in before {
          let selected = sticker.position.isOnLayer(rotation.axis)
          let actual = selected ? rotation.applying(to: sticker) : sticker
          var destination = sticker.index
          for _ in 0..<Int(turns.rawValue) {
            destination = goldenQuarterTurns[Int(face.rawValue)][destination]
          }
          let expected = before[destination]
          try #require(actual.position == expected.position && actual.normal == expected.normal)
          #expect(actual.index == sticker.index)
          if !selected { #expect(actual == sticker) }
        }
      }
    }
  }
}

@Test("V10: regrips move all geometry without changing sticker identity and invert exactly")
func cubeGeometryRegrips() throws {
  for pose in CubeOrientation.all {
    for operation in Regrip.allCases {
      let rotation = CubeRotation(regrip: operation)
      let inverse = CubeRotation(regrip: operation.inverse)
      for sticker in CubeGeometry.stickers {
        let before = sticker.viewed(at: pose)
        let after = rotation.applying(to: before)
        try #require(after == sticker.viewed(at: pose.regripped(operation)))
        #expect(inverse.applying(to: after) == before)
      }
      #expect(Set(CubeGeometry.cubies.map { rotation.applying(to: $0) }) == Set(CubeGeometry.cubies))
    }
  }
}

@Test("V10: animation angles take the short inverse turn and agree with exact right-handed rotations")
func cubeGeometryAnimationAngles() throws {
  for face in Face.allCases {
    for (turns, expected) in [(QuarterTurns.clockwise, -1), (.half, -2), (.counterclockwise, 1)] {
      let rotation = CubeRotation(axis: face, turns: turns)
      try #require(rotation.signedQuarterTurns == expected)
      let axis = CubeGeometry.axis(for: face)
      for point in CubeGeometry.cubies {
        // Independent right-handed integer Rodrigues step; no production pose mapping.
        var p = point
        for _ in 0..<abs(expected) {
          let dot = axis.x * p.x + axis.y * p.y + axis.z * p.z
          let sign = expected < 0 ? -1 : 1
          p = CubePosition(
            x: axis.x * dot + sign * (axis.y * p.z - axis.z * p.y),
            y: axis.y * dot + sign * (axis.z * p.x - axis.x * p.z),
            z: axis.z * dot + sign * (axis.x * p.y - axis.y * p.x))
        }
        #expect(rotation.applying(to: point) == p)
      }
    }
  }
}

@Test("V02/V10: all 24 geometric poses match the independently qualified facelet view grids")
func cubeGeometryPoses() throws {
  let resting = CubeGeometry.stickers
  for pose in CubeOrientation.all {
    let placed = resting.map { $0.viewed(at: pose) }
    var sourcesAtDestination = Array(repeating: -1, count: 54)
    for sticker in placed {
      let destination = try #require(resting.firstIndex {
        $0.position == sticker.position && $0.normal == sticker.normal
      })
      sourcesAtDestination[destination] = sticker.index
    }
    try #require(sourcesAtDestination == pose.viewing(Array(0..<54)))
    // The physical top edge follows the row above each center. This checks label
    // orientation against positions already compared with the canonical view grid.
    for face in Face.allCases {
      let top = placed[Int(face.rawValue) * 9 + 1]
      let center = placed[Int(face.rawValue) * 9 + 4]
      let direction = CubeGeometry.axis(for: center.top)
      #expect(top.position.x - center.position.x == direction.x)
      #expect(top.position.y - center.position.y == direction.y)
      #expect(top.position.z - center.position.z == direction.z)
    }
    #expect(Set(CubeGeometry.cubies.map { $0.viewed(at: pose) }) == Set(CubeGeometry.cubies))
  }
}
