#!/usr/bin/env python3
"""Test fixtures only: integer geometry derived from specification face bases.
Never imported by the product or table generator. Destination arrays are source→destination.
"""
import json
from pathlib import Path

def add(a,b): return tuple(x+y for x,y in zip(a,b))
def scale(a,k): return tuple(x*k for x in a)
def dot(a,b): return sum(x*y for x,y in zip(a,b))
def cross(a,b): return (a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0])
def rotate(v,n): return add(scale(n,dot(n,v)),scale(cross(n,v),-1))
bases=[((0,1,0),(1,0,0),(0,0,-1)),((1,0,0),(0,0,-1),(0,1,0)),((0,0,1),(1,0,0),(0,1,0)),((0,-1,0),(1,0,0),(0,0,1)),((-1,0,0),(0,0,1),(0,1,0)),((0,0,-1),(-1,0,0),(0,1,0))]
stickers=[(add(add(n,scale(r,c-1)),scale(u,1-row)),n) for n,r,u in bases for row in range(3) for c in range(3)]
lookup={s:i for i,s in enumerate(stickers)}
assert len(lookup)==54
moves={}
for face,(normal,_,_) in zip('URFDLB',bases):
    destinations=[lookup[(rotate(p,normal),rotate(n,normal))] if dot(p,normal)==1 else i for i,(p,n) in enumerate(stickers)]
    assert sorted(destinations)==list(range(54))
    moves[face]=destinations
root=Path(__file__).resolve().parents[2]
(root/'Fixtures/Mathematics/quarter-turns.json').write_text(json.dumps(moves,indent=2)+'\n')
# Swift literal fixtures allow SPM tests to run without depending on a working directory.
body='// Generated by Tools/FixtureGenerator/golden_moves.py. Test-only source→destination fixtures.\nlet goldenQuarterTurns: [[Int]] = [\n'
body+='\n'.join('    '+str(moves[f])+',' for f in 'URFDLB')+'\n]\n'
(root/'Packages/CubeKit/Tests/CubeCoreTests/GoldenMoves.swift').write_text(body)
